### Register
POST http://localhost:8000/register HTTP/1.1
Content-Type: application/json

{
    "username": "arjun",
    "password": "arjun",
    "email": "arjun@gmail.com",
    "mobile": "1234569999"
}

### Login
POST http://localhost:8000/login HTTP/1.1
Content-Type: application/json

{
    "username": "ammu",
    "password": "ammu"
}

### Logout
DELETE http://localhost:8000/logout HTTP/1.1
Authorization: 01abe6a8-3dea-4b19-bf64-2f4d8690f315



### List Posts
GET http://localhost:8000/posts HTTP/1.1
Authorization: 0ca26dd8-6b4a-4327-a666-523ce5f39297

### Create Post
POST http://localhost:8000/posts HTTP/1.1
Content-Type: application/json
Authorization: 0ca26dd8-6b4a-4327-a666-523ce5f39297

{
    "content": "This is my third post"
}

### Get Post
GET http://localhost:8000/posts/6 HTTP/1.1
Authorization: 18c47388-9a9f-497e-bc86-e329fb352510

### Update Post
PUT http://localhost:8000/posts/2 HTTP/1.1
Content-Type: application/json
Authorization: 417fa674-1602-4ca6-bed6-9d9239f82151

{
    "content": "1 updated post "
}

### Delete Post
DELETE http://localhost:8000/posts/1 HTTP/1.1
Authorization: 0681a541-d0a9-4cc0-a08f-2743f3147c5f



### Get comment
GET http://localhost:8000/posts/1/comments HTTP/1.1
Content-Type: application/json
Authorization: 0681a541-d0a9-4cc0-a08f-2743f3147c5f

### Create comment
POST http://localhost:8000/posts/1/comments HTTP/1.1
Content-Type: application/json
Authorization: 3bb19959-0c34-4b1f-9d61-54de3ab2d51e

{
    "body": "This is my comment 2"
}

# ### Delete comment
# DELETE http://localhost:8000/